#
# SPDX-FileCopyrightText: 2023-2025 Aayush Gupta <aayushgupta219@gmail.com>
# SPDX-License-Identifier: Apache-2.0
#

image: docker:latest

services:
  - docker:dind

before_script:
  - echo "${CI_REGISTRY_PASSWORD}" | docker login -u ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY}

build:
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG == null && $CI_COMMIT_REF_PROTECTED == "true"'
      when: always
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"

tag:
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG != null'
      when: always
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
