#
# SPDX-FileCopyrightText: 2023-2025 Aayush Gupta <aayushgupta219@gmail.com>
# SPDX-License-Identifier: Apache-2.0
#

# This follows the REUSE specification: https://reuse.software/spec-3.2/#reusetoml

version = 1

[[annotations]]
path = [
    "packages.txt",
    "README.md",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023-2025 Aayush Gupta <aayushgupta219@gmail.com>"
SPDX-License-Identifier = "Apache-2.0"
